[Display]
gpioMapping = "adafruit-hat-pwm"
rows = "16"
cols = "32"
chain = "4"
pwmBits = "11"
slowdownGpio = "1"
scanMode = "0"
pixelMapper = "u-mapper"

# this pin is set to high when ready
powerLED = "0"
